marklogic/node-client-api

- etc/marklogic-template/static/styles/site.marklogic.css
Previous color was too light and not consistent with color scheme. Fixes issue #92
> Change JSDoc menu item hover color to light blue

- test-complete/data/people2.ttl
> Add missing predicate to ppl:person1 triple

- CONTRIBUTING.md
- LICENSE
> Adds license and updates contribution guidelines

- lib/marklogic.js
- lib/operation.js
- lib/requester.js
- package.json
> Add support for Kerberos authentication

- lib/documents.js
- test-basic/documents-core.js
> Added support for metadata values

- lib/query-builder.js
- test-basic/query-builder.js
> Add support for geospatial polygon search

- KERBEROS.md
- README.md
> Add documentation for Kerberos authentication support

- lib/patch-builder.js
- test-basic/documents-patch.js
> Add metadata value patch operations and tests

- lib/documents.js
> Update documentation for transform params

- README.md
- package.json
@ayuwono @jmakeig please review.
> Update README for 1.0.6 release

- lib/resources-config.js
- lib/transforms.js
- test-basic/documents-transform.js
- test-basic/resources-config.js
Converts returned Buffer object to string.
Fixes #269
> Output transforms for read() in config.resources and config.transforms

- lib/marklogic.js
> Add certificate authentication

- test-basic/documents-core.js
Ensure that the new capability is covered in test-basic.
> Test for "node-update" document-level capability

- lib/query-builder.js
- test-basic/query-builder.js
> Support minimum-distance param in near query

- etc/test-setup-users.js
- lib/documents.js
- lib/marklogic.js
- lib/mlutil.js
- lib/patch-builder.js
- lib/query-builder.js
- test-basic/documents-temporal-document.js
- test-basic/documents-temporal-patch.js
- test-basic/documents-temporal-protect.js
- test-basic/documents-temporal-wipe.js
Includes protect, wipe, and patch
Methods and tests
Fixes #294
> Add temporal features

- lib/documents.js
- test-basic/documents-temporal-protect.js
> Check directory existence for archivePath

- test-basic/documents-temporal-protect.js
> Remove comment, protect() expireTime now works

- test-basic/documents-temporal-protect.js
Add a test that protects a file twice, sequentially
> Clean up protect() tests

- lib/requester.js
> Add ML-Agent-ID header to all REST requests

- lib/query-builder.js
the operators crosses, equals, and touches are not supported
> edit docs to remove unsupported spatial operators

- lib/documents.js
- test-basic/documents-core.js
> Remove support and test for lang parameter in document writes

- lib/values-builder.js
Appropriate documentation for geoOptions() will now show up.
Fixes #251
> fix(#251): Fix reference to geoOption() -> geoOptions()

- lib/documents.js
- test-basic/probe.js
> fix(#255): enable probe() to accept params as list or object

- lib/mlutil.js
- test-basic/errors.js
https://github.com/v8/v8/wiki/Stack-Trace-API#stack-trace-collection-for-custom-exceptions
Fixes #297
> fix(#297): add stack trace to server errors

- lib/marklogic.js
> update setSliceMode description

- etc/marklogic-template/tmpl/container.tmpl
An attempt to fix XML validation errors when deploying doc content to pubs server. #372
> remove whitespace in h2 of container.tmpl

- lib/transforms.js
> Update docs to include 'javascript' as an option for transform write

- lib/graphs.js
- test-basic/graphs.js
Params each take one or more graph URIs, not a boolean
Fixes #383
> fix(#383): Change usingDefaultGraphs and usingNamedGraphs param types

- KERBEROS.md
> task(#328): Update KERBEROS.md with --no-optional info

- README.md
> README updates for version 2.0.1

- package.json
- test-basic/query-builder.js
Updated gulp-mocha from 3.0.1 to 4.1.0
Also removed a console.log call
> Update gulp-mocha dependency

- KERBEROS.md
- README.md
- lib/documents.js
- lib/patch-builder.js
- lib/query-builder.js
- lib/values-builder.js
- package.json
- test-basic/data/echoModule.js
- test-complete/nodejs-documents-transaction-timelimit.js
Includes documentation and test updates.
> Merge develop with 2.0.0-rc

- lib/operation.js
- lib/responder.js
- test-basic/documents-core.js
- test-basic/documents-query.js
Fixes object-stream-handling issues: #362, #419
> Refactor dispatch handling

- lib/rows.js
- test-basic/data/literalsAttachments.json
- test-basic/rows.js
> Add queryAsStream(), handle attachments, refactoring, comments

- lib/operation.js
- lib/responder.js
- lib/rows.js
- test-basic/data/literalsAttachments.sjs
- test-basic/data/literalsBinaryAttachments.json
- test-basic/data/literalsBinaryAttachments.sjs
- test-basic/rows.js
Also: change 'nodeColumns' property to 'complexValues'
> Add rows handling for reference attachments

- lib/graphs.js
- test-basic/documents-query.js
- test-basic/graphs.js
Both for document query and sparql query
> Add tests for combined query

- lib/documents.js
- lib/patch-builder.js
- lib/requester.js
- lib/responder.js
Addresses medium-level issues.
Fixes #375
> Address issues highlighted by static analysis

- examples/before-load.js
Use Promise.all() to write batches of files only after all example files in batch have been read.
> Fix async loading of example files

- lib/documents.js
Related to recently committed advanceLsqt() method
> Fix jshint warnings

- etc/data/employees.tdej
- etc/test-setup.js
- test-basic/rows.js
Includes template loading in test-setup.js.
> Add TDE view test to Optic tests in rows.js

- test-basic/data/echoModule.js
- test-basic/server-exec.js
Addresses change in date handling in Node.js version 8.
Fixes #475
> Remove timezone ('Z') from test data

- lib/documents.js
- lib/graphs.js
- lib/rows.js
- lib/values.js
> Fix JSDoc timestamp references

- lib/rows.js
- test-basic/client.js
- test-basic/rows.js
Also add test for this. Fixes #478.
> Add database param for rows queries if exists

- lib/query-builder.js
- test-basic/query-builder.js
Fix for https://github.com/marklogic/node-client-api/issues/508
> added beforeQuery and afterQueryquery to queryBuilder

- lib/mlutil.js
- test-basic/graphs.js
Fix for - https://github.com/marklogic/node-client-api/issues/524
> graphs.sparql: binding an array of values

- lib/patch-builder.js
- test-basic/patch-builder.js
Fix for - https://github.com/marklogic/node-client-api/issues/487
> support SJS content generators for patch operations

- lib/documents.js
- lib/graphs.js
- lib/mlutil.js
- lib/resources-exec.js
- lib/server-exec.js
- lib/transactions.js
- test-basic/transactions.js
Fix for - https://github.com/marklogic/node-client-api/issues/499
> Allowing to pass transaction object between services.

- lib/resources-exec.js
- test-basic/documents-query.js
Unit test for streaming errors - https://github.com/marklogic/node-client-api/issues/479 and adding null check for transaction id.
> Unit test for stream error handler and adding null check for transaction id.

- etc/test-config.js
- etc/test-setup-users.js
- test-basic/documents-quick.js
> Created a user and role to verify the connection under different

- config-optic/connectdef.js
- etc/marklogic-template/static/scripts/fulltext-search-ui.js
- etc/marklogic-template/static/scripts/fulltext-search.js
- etc/marklogic-template/static/scripts/toc.js
- examples/read-rows.js
- test-basic/client.js
- test-basic/graphs.js
- test-basic/rows.js
- test-complete/nodejs-documents-patch-metadata.js
- test-complete/nodejs-documents-query-3.js
- test-complete/nodejs-documents-query.js
- test-complete/nodejs-graphs-content-type.js
- test-complete/nodejs-graphs-default.js
- test-complete/nodejs-graphs-merge.js
- test-complete/nodejs-javascript-eval.js
- test-complete/nodejs-optic-cts-queries.js
- test-complete/nodejs-optic-from-lexicons.js
- test-complete/nodejs-optic-from-literals.js
- test-complete/nodejs-optic-from-sparql.js
- test-complete/nodejs-optic-from-sql.js
- test-complete/nodejs-optic-from-triples.js
- test-complete/nodejs-optic-from-views.js
- test-complete/nodejs-optic-nodes.js
- test-complete/nodejs-optimistic-locking.js
- test-complete/nodejs-process-env.js
- test-complete/nodejs-sparql-update.js
- test-complete/nodejs-sparql.js
- test-complete/nodejs-temporal-advance-lsqt.js
- test-complete/nodejs-temporal-period-compare-query.js
- test-complete/nodejs-temporal-update-lsqt.js
instead of relying on automatic semicolon insertion, which can result in errors and unexpected behaviors.
> Add semicolons for unterminated statements 

- lib/ctsquery-builder.js
- lib/marklogic.js
- lib/plan-builder-base.js
- lib/query-builder.js
- test-basic/documents-query.js
> #562 - cts.query builder

- lib/plan-builder-generated.js
- lib/plan-builder.js
- lib/rows.js
- test-basic/plan-builder-base.js
- test-basic/plan-processors.js
Adding generateView() in rows.js
> #569 -  Optic enhancements in 10.0-7

- lib/marklogic.js
Fix for issue - https://github.com/marklogic/node-client-api/issues/570
> #570 - Changing testConnection to testConnection

- lib/rows.js
- test-basic/rows.js
Fix for issue - https://github.com/marklogic/node-client-api/issues/485
> #485 - Throw error when complexValues is set with a chunked stream

- etc/test-setup-users.js
Adding rest-evaluator role to rest-writer.
> #579 - Jenkins failure - Tests in probe.js

- lib/endpoint-proxy.js
- test-basic/endpoint-caller.js
- test-basic/service-caller.js
Adding unit tests for Endpoint caller and an additional test for serviceCaller
> Endpoint Caller unit tests.

- lib/plan-builder.js
- lib/rows.js
- test-basic/endpoint-caller.js
- test-basic/plan-processors.js
- test-basic/redactionTest.js
- test-basic/service-caller.js
Unit tests for redaction and generate-view
> Unit tests for redaction and generate-view.

- CHANGELOG.md
Adding CHANGELOG.md file stating the new functionalities and bug fixes.
> Adding CHANGELOG.md file.

- lib/documents.js
- test-basic/documents-data-movement-queryAll.js
#622 - Unit tests for queryAll api.
> Unit tests for queryAll api.

- lib/documents.js
#622 - Documentation for queryAll api.
Jira - https://project.marklogic.com/jira/browse/NODE-28
> Document the queryAll api.

- lib/documents.js
- npm-shrinkwrap.json
- package.json
- test-basic/documents-data-movement-ingest.js
- test-basic/documents-data-movement-readAll.js
https://github.com/marklogic/node-client-api/issues/620 - readAll api - Implementation and Unit tests for batchSize, onCompletion, concurrentRequests, inputKind and outputStreamType
> readAll api - Implementation and Unit tests for batchSize, onCompletion, concurrentRequests, inputKind and outputStreamType

- examples/queryAll-documents.js
- test-basic/documents-data-movement-queryAll.js
https://github.com/marklogic/node-client-api/issues/622
> Include an example for queryAll api and few fixes in the unit test file.

- lib/documents.js
- test-basic/documents-data-movement-queryAll.js
- test-basic/documents-data-movement-readAll.js
https://github.com/marklogic/node-client-api/issues/622 - Added onInitialTimestamp and updated consistentSnapshot options for queryAll api
https://github.com/marklogic/node-client-api/issues/620 - Updated consistentSnapshot option for readAll api.
> Adding onInitialTimestamp and changes for consistentSnapshot

- lib/documents.js
- test-basic/documents-data-movement-queryAll.js
- test-basic/documents-data-movement-readAll.js
https://github.com/marklogic/node-client-api/issues/620 -  Implementation, unit tests and JS docs for queryToReadAll api.
> queryToReadAll - Implementation, unit tests and JS docs.

- test-basic/graphs.js
https://github.com/marklogic/node-client-api/issues/638
> Unit test for parameters begin and end.

- test-basic/documents-data-movement-ingest.js
Adding cleanup for ingest test.
> Adding cleanup for ingest test.

- lib/documents.js
https://github.com/marklogic/node-client-api/issues/621
> Fixing few typing errors in writeAll api.

- lib/documents.js
- test-basic/documents-data-movement-readAll.js
https://github.com/marklogic/node-client-api/issues/647
> Fix for - QueryToReadAll on a Query with no results produces no response

- CHANGELOG.md
https://github.com/marklogic/node-client-api/issues/553
> CHANGELOG.md update for 2.9.0 release.

- examples/queryToReadAll-documents.js
- lib/documents.js
https://github.com/marklogic/node-client-api/issues/620 - Example to use queryToReadAll
> Include an example to use queryToReadAll and JS docs fix.

- CHANGELOG.md
Adding https://github.com/marklogic/node-client-api/issues/599 to CHANGELOG.md
> Adding github issue 599 to CHANGELOG.md for 2.9.0 release

- test-basic/plan-documents.js
https://github.com/marklogic/node-client-api/issues/592
> NODE-59: Add unit test(s) for op:sample-by in Node Client API

- lib/documents.js
- test-basic/documents-data-movement-transformAll.js
https://github.com/marklogic/node-client-api/issues/644 - Implementation, unit tests and JS docs for queryToTransformAll api.
> Implementation, unit tests and JS docs for queryToTransformAll api.

- lib/documents.js
- test-basic/documents-data-movement-removeAllUris.js
https://github.com/marklogic/node-client-api/issues/665
> NODE-31 Deleting Documents. Initialization, Operation, Finalization.

- examples/queryToRemoveAll-documents.js
- examples/removeAllUris-documents.js
- lib/documents.js
- test-basic/documents-data-movement-removeAllUris.js
https://github.com/marklogic/node-client-api/issues/665 - Documentation and examples for removeAllUris and queryToRemoveAll
> NODE-71 and NODE-75: Documentation and examples for removeAllUris and queryToRemoveAll

- etc/test-config.js
- etc/test-setup-users.js
- lib/rows.js
- npm-shrinkwrap.json
- package.json
- test-basic/data/exportingRows.tdex
- test-basic/documents-data-movement-rows-queryAll.js
https://github.com/marklogic/node-client-api/issues/614 - Implementation, unit tests and JS docs.
> NODE-6 : Exporting Rows-Implementation, unit tests and JS docs.

- examples/queryAll-rows.js
- test-basic/documents-data-movement-rows-queryAll.js
https://github.com/marklogic/node-client-api/issues/614 - Include an example for queryAll in the examples folder
> NODE-77 : Include an example for queryAll in the examples folder

- lib/documents.js
- test-complete/nodejs-dmsdk-removeAllUris.js
https://project.marklogic.com/jira/browse/NODE-76
> NODE-76 : Functional tests for removeAllUris and queryToRemoveAll

- lib/plan-builder-generated.js
- test-basic/plan-builder-generated.js
https://project.marklogic.com/jira/browse/JAVA-263
> Adding the new auto generated optic functions

- package.json
https://project.marklogic.com/jira/browse/DEVEXP-72
> Upgrade dependencies in Node-client version 2.9.0

- package.json
> NODE-82: Upgrade dependencies reported as "high" vulnerability

- lib/plan-builder-generated.js
- lib/server-types-generated.js
- test-basic/plan-builder-generated.js
https://project.marklogic.com/jira/browse/NODE-87
> NODE-87 : Update the auto-generated file in Node Client Api

- lib/mlutil.js
- test-basic/cloud_authentication-test.js
> NODE-117 : Read and write to a database different from "Documents" on ML cloud instance does not work.

- examples/readAll-documents.js
- examples/removeAllUris-documents.js
- examples/transformAll-documents.js
- examples/writeAll-documents.js
- lib/documents.js
- lib/rows.js
- package-lock.json
- package.json
- test-basic-proxy/lib/positive/sessionsTest.js
- test-basic/documents-data-movement-ingest.js
- test-basic/documents-data-movement-queryAll.js
- test-basic/documents-data-movement-readAll.js
- test-basic/documents-data-movement-removeAllUris.js
- test-basic/documents-data-movement-rows-queryAll.js
- test-basic/documents-data-movement-transformAll.js
- test-basic/unnestTest.js
- test-complete/nodejs-dmsdk-QueryToRdAll.js
- test-complete/nodejs-dmsdk-UpdAndRdAll.js
- test-complete/nodejs-dmsdk-queryToTransformAll.js
- test-complete/nodejs-dmsdk-queryall.js
- test-complete/nodejs-dmsdk-readall-1.js
- test-complete/nodejs-dmsdk-removeAllUris.js
- test-complete/nodejs-dmsdk-rows-queryAll.js
- test-complete/nodejs-dmsdk-transformAll.js
- test-complete/nodejs-dmsdk-txtFiles-transformAll.js
- test-complete/nodejs-dmsdk-writeall.js
- test-complete/nodejs-dmsdk-xmlFiles-transformAll.js
Fix for -
NODE-111 : Upgrade the Node-Client-Api to support an upgraded NODE 18
Jenkins test failures.
https://github.com/marklogic/node-client-api/issues/713
> NODE-111 : Upgrade Node-Client-Api to support an upgraded NODE 18

- examples/unnest-function.js
Adding an example of how an end user can use the unnest functions.
>  NODE-124: Add an example for using unnest functions

- lib/responder.js
- test-basic/optic-update-execute.js
the tests are passing as expected in windows machine
> DEVEXP-289: The "remove" optic function throws a multipart error

- lib/internal.js
- test-basic/test-internal.js
This adds the ability to add a body to POST requests.
Also updated the automated tests.
> Add more flexibility to the internal sendRequest function.

- lib/internal.js
- lib/marklogic.js
- lib/mlutil.js
- test-basic/test-internal.js
> DEVEXP-502 : In the Node client: internal.js has two global variables that should be refactored

- test-basic/documents-data-movement-rows-queryAll.js
This is temporary. Will be rolling back when we find the ROWID issue.
> Fix for jenkins pipeline hang issue

- README.md
- examples/marklogic-cloud-connection.js
Adding the same example in "develop" branch so that it is not missed during release.
> DEVEXP-587 : Update README to include an example for connecting to MarkLogic Cloud

- package-lock.json
- test-basic/documents-data-movement-rows-queryAll.js
- test-basic/optic-fromDocUris.js
- test-basic/plan-builder-generated.js
- test-basic/plan-views.js
This PR address the following -
1. DBQ-559 : Jenkins pipeline hang on running RowBatcher tests
2. Few things left out in https://github.com/marklogic/node-client-api/pull/799
3. Changes in package-lock.json
> DBQ-559 : Jenkins pipeline hang on running RowBatcher tests

- README.md
…
This reverts commit 69695120ae6075870a730da8f5b7691229ab1af7.
> Revert "DEVEXP-587 : Update README to include an example for connecting to MarkLogic Cloud"

- etc/test-setup-qa.js
- test-complete/nodejs-documents-query-2.js
- test-complete/nodejs-documents-query-3.js
- test-complete/nodejs-documents-query.js
- test-complete/nodejs-temporal-protect-update.js
Cleaned up the stemming tests and skipped the Temporal tests.
> Clean up the stemming tests.

- CHANGELOG.md
- package-lock.json
- package.json
https://github.com/advisories/GHSA-cgfm-xwp7-2cvr
> Fix for Security vulnerability - sanitize-html

- package-lock.json
- package.json
https://nvd.nist.gov/vuln/detail/CVE-2024-4068 
and https://github.com/advisories/GHSA-7fh5-64p2-3v2j
> Fix for vulnerabilities

- lib/plan-builder-generated.js
- lib/server-types-generated.js
- test-basic/plan-builder-generated.js
(This generation was conducted after replacing hints file with the one in develop branch.)
> MLE-15255 : Run the autogeneration of new Optic Code for Node Client

- test-app/build.gradle
- test-app/docker-compose.yaml
- test-app/src/main/ml-config/security/certificate-templates/template.xml
- test-app/src/main/ml-config/servers/ssl-server.json
Should make it easier to write tests that test SSL with the Node Client.
> Added an app server that requires SSL
