lib/graphs.js
This bug fix supports the shortcut way of calling graph.sparqlUpdate(). The method can also be called with a configuration object.
closes #236
=> handle sparqlUpdate request as single string arg

lib/graphs.js
=> correctly handle default graphs in multi-param sparql()

lib/requester.js
authenticatedRequest() is called twice, and neither call uses a return value, so safe to remove "return request".
operation.requestBodyProvider property is never set, so safe to remove the logic that acts on it.
=> remove unnecessary code in requester.js

lib/resources-exec.js
Allows cases where the documents property is not defined.
Fixes #257
=> Check if documents property is undefined for a resource PUT or POST

lib/documents.js
=> Handle metadataValues category for documents.patch().

lib/optional.js
ES6 features cause issues with earlier versions of Node.js.
=> Use var instead of const in variable declaration

package.json
A renaming has broken apps that depend on gulp-jsdoc:
https://github.com/hegemonic/taffydb/pull/1
=> Remove gulp-jsdoc dep from package.json until taffydb issue is fixed

npm-shrinkwrap.json, package.json
Similar to what jsdoc is doing:
https://github.com/jsdoc3/jsdoc/commit/de87a1b3f49bd360c5ef10c9edc7bd12bd8e96df
=> Use npm-shrinkwrap to work around gulp-jsdoc issue

lib/documents.js
=> Update documentation for transform params

lib/query-builder.js
NearDef() inherits from QueryDef()
Fixes #316
=> Refactor near() to use NearDef()

lib/query-builder.js
To avoid false positives, you can turn on the word positions index or enable filtering
=> update docs for near() requirements

lib/values-builder.js
For geospatial() and geospatialRegion().
Fixes #250
=> fix(#250): add borrows JSDoc references to values-builder.js

lib/documents.js, lib/marklogic.js, lib/mlutil.js, lib/query-builder.js, lib/transactions.js, test-basic/documents-query.js, test-basic/documents-quick.js, test-basic/documents-transform.js, test-basic/extlibs.js, test-basic/query-builder.js, test-basic/values-builder.js, test-basic/values.js
- legacy non-array return values for remove() methods
- default return values for transactions.open() (change from transaction ID to object)
- default slice mode (change from "legacy" to "array")
=> fix(#231): address deprecated features

lib/bluebird-plus.js, lib/documents.js, lib/query-builder.js, package.json
Updated dependencies to current versions based on running "npm outdated".
Updated file path for new version of bluebird.
Fixed minor linting errors.
=> task(#343): update dependencies in package.json

jsdoc.json, lib/marklogic.js
Add methodHeadingReturns option for jsdoc to display return values with methods.
Tag marklogic as a namespace instead of module to address the fact that, with marklogic as a module, jsdoc is not recognizing methods of marklogic such as createDatabaseClient(). Fixes #372.
=> Fix issues in jsdoc generation

test-basic/suggest.js
Test often fails due to timeout, extend from default 2000 ms to 3000 ms.
=> Extend timeout for suggest test

README.md, lib/documents.js, lib/extlibs.js, lib/graphs.js, lib/marklogic.js, lib/patch-builder.js, lib/query-builder.js, lib/resources-config.js, lib/resources-exec.js, lib/rest-server-properties.js, lib/server-exec.js, lib/transactions.js, lib/transforms.js, lib/values-builder.js, lib/values.js
=> fix(#303): Update README with compatibility info

lib/documents.js, lib/query-builder.js
=> fix(#227): clarify when a summary object appears in query results

lib/responder.js
From dispatchMultipartObjectStream, check that HTTP response has ended, Dicer has finished parsing, and the Queue is empty.
Fixes #362
=> Handle when multipart object stream is done

lib/values-builder.js
Now uses array slice mode by default, same as queryBuilder.
Updates docs and fixes #400 
See https://github.com/marklogic/node-client-api/issues/231#issuecomment-296404227
=> Update docs for valuesBuilder.BuiltQuery#slice

package.json, test-basic/logging.js
Tests default, Bunyan, and Winston loggers.
Leverages the intercept-stdout library for reading stdout log entries.
=> Add tests of logging

lib/operation.js, lib/responder.js, test-basic/documents-core.js, test-basic/documents-query.js
- Simplify the multipart object stream path. No longer use QueuedReader; instead write directly to the through2 output stream.
- Separate  object creation and object queuing for the multipart promise and multipart object stream cases. operation.makeObject() handles object creation; queuing (or writing) of the made objects is handled in the responder.
- Track metadata objects in a this.nextMetadataBuffer property in operation. 
- Add comments.
=> Refactor promise and object stream dispatches

lib/operation.js, lib/responder.js
jsdoc script should not process responseDispatcher() or makeObject() for public API docs
=> Ignore documentation of internal methods

lib/graphs.js
Corrects parameter naming
Fixes #437
=> Fix graphs#sparql documentation, 'documentQuery' to 'docQuery'

test-basic/documents-temporal-protect.js
Rewritten so the archivePath test can be skipped by Jenkins, see:
https://bugtrack.marklogic.com/45783
=> Rewrite temporal protect tests

package.json
See: https://github.com/marklogic/node-client-api/issues/459
=> Up Node.js version support to 6.9.0.

README.md, npm-shrinkwrap.json, package.json
Added the missing `moment` and `sanitize-html` dependencies.
Wrapped the various script executables into the `package.json` scripts
block, also updating the README.md to reflect it.
=> Fixes #514: Adds missing deps and npm scripts

test-basic/documents-query.js
Fix for - https://github.com/marklogic/node-client-api/issues/341
=> queryBuilder.extract now accepts namespace bindings

lib/marklogic.js, lib/responder.js, test-basic/documents-quick.js
Enhancement feature referring to - https://github.com/marklogic/node-client-api/issues/346
=> Adding feature for - "Test Connection"

lib/marklogic.js
MarkLogic server prefers ipv4 addresses to ipv6 addresses.
Because the client's address factors into validation of the nonce in DIGEST authentication, the client must continue to use the same address while using the nonce.
=> #543 - prefer ipv4 to ipv6 addresses

lib/marklogic.js
rejectUnauthorized option ignored in webpacked typescript (impacts mlxprs extension in latest VSCode on Mac)
Fix for issue - https://github.com/marklogic/node-client-api/issues/568
=> #568 - rejectUnauthorized option ignored in webpacked typescript (impacts mlxprs extension in latest VSCode on Mac)

lib/documents.js, test-basic/documents-data-movement-readAll.js
https://github.com/marklogic/node-client-api/issues/620 - Implementation for chunked outputStreamType and unit tests for transform, categories, consistentSnapshot and onBatchError.
=> readAll api - Implementation for chunked outputStreamType and unit tests for transform, categories, consistentSnapshot and onBatchError.

examples/queryToTransformAll-documents.js, examples/transformAll-documents.js, lib/documents.js, lib/responder.js
1. https://github.com/marklogic/node-client-api/issues/644 - Adding example for transformAll and queryToTransformAll in the examples folder.
2. Indentation fixes for - https://github.com/marklogic/node-client-api/pull/666
=> NODE-72: Include examples for transformAll and queryToTransformAll.

README.md
Updating README for - https://github.com/marklogic/node-client-api/issues/694
=> Node-89 : MarkLogic module v 2.9.1 for Node.js at Windows OS does not work.

test-complete-proxy/nodejs-ds-error-map.js
A one line change to make tests run without error in Node JS ver. 18.14.2
=> DEVO-762 Changes to remove QA test error

test-complete/nodejs-documents-transaction-timelimit.js
Mocha does not guarantee "it" blocks are run sequentially or that they are non-synchronous.
Therefore, this "set" of tests really needs to be a single test with a chain of promises in order to guarantee order and timing.
=> Fix the transaction time limit test

Jenkinsfile, test-complete/nodejs-dmsdk-queryall.js
It seems like some of the mocha tests have unintended interactions. So, this should ensure that the test files are run one at a time.
Also, surrounded some cleanup code with a try-catch block for when the test fails and nothing is there to clean up.
=> Unparallelize Mocha tests

Jenkinsfile
=> MLE-17863 : Jenkins nightly builds intermittently throw errors due to gulp global installation.
